spring:
  application:
    name: oauth2-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      password: 123456
      username: root
  redis:
    database: 0
    password: Asd4840840
    port: 6379
    host: 193.112.249.143
  security:
    oauth2:




server:
  port: 8080

mybatis:
  type-aliases-package: com.funtl.oauth2.server.domain
  mapper-locations: classpath:tk/mybatis/mapper/*.xml